CREATE TABLE active_principle
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_activeprinciple PRIMARY KEY (id)
);

CREATE TABLE animal
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id      BIGINT                                  NOT NULL,
    animal_mother_id BIGINT                                  NOT NULL,
    breed_id         BIGINT                                  NOT NULL,
    type             VARCHAR(255),
    identifier       VARCHAR(255),
    gender           VARCHAR(255),
    born_condition   VARCHAR(255),
    born_date        date,
    born_weight      FLOAT,
    previous_weight  FLOAT,
    current_weight   FLOAT,
    ecc              FLOAT,
    CONSTRAINT pk_animal PRIMARY KEY (id)
);

CREATE TABLE animal_diseases
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diagnosis      VARCHAR(255),
    diagnosis_date date,
    animal_id      BIGINT,
    CONSTRAINT pk_animaldiseases PRIMARY KEY (id)
);

CREATE TABLE animal_purchases
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_purchase date,
    birth_date    date,
    value         DECIMAL,
    animal_id     BIGINT,
    CONSTRAINT pk_animalpurchases PRIMARY KEY (id)
);

CREATE TABLE animal_sales
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_sale   date,
    reason      SMALLINT,
    value       DECIMAL,
    destination SMALLINT,
    animal_id   BIGINT,
    CONSTRAINT pk_animalsales PRIMARY KEY (id)
);

CREATE TABLE breed
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    breed_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_breed PRIMARY KEY (id)
);

CREATE TABLE change_password
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recuperation_code    VARCHAR(255),
    code_submission_date TIMESTAMP WITHOUT TIME ZONE,
    recuperation_email   VARCHAR(255),
    user_display_name    VARCHAR(255),
    new_password         VARCHAR(255),
    CONSTRAINT pk_changepassword PRIMARY KEY (id)
);

CREATE TABLE city
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    city_region_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_city PRIMARY KEY (id)
);

CREATE TABLE culture
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    culture_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_culture PRIMARY KEY (id)
);

CREATE TABLE disease
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    disease_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_disease PRIMARY KEY (id)
);

CREATE TABLE email
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_ref       VARCHAR(255),
    email_from      VARCHAR(255),
    email_to        VARCHAR(255),
    subject         VARCHAR(255),
    text            TEXT,
    send_date_email TIMESTAMP WITHOUT TIME ZONE,
    status_email    VARCHAR(255),
    CONSTRAINT pk_email PRIMARY KEY (id)
);

CREATE TABLE forage_disponibility
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        date,
    forage      VARCHAR(255),
    entry       FLOAT,
    residue     FLOAT,
    kg          FLOAT,
    picket_area FLOAT,
    efficiency  FLOAT,
    num_cows    DECIMAL,
    kg_cows     FLOAT,
    property_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_foragedisponibility PRIMARY KEY (id)
);

CREATE TABLE insemination
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ia_date   date,
    bull      VARCHAR(255),
    animal_id BIGINT,
    CONSTRAINT pk_insemination PRIMARY KEY (id)
);

CREATE TABLE land_product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id BIGINT                                  NOT NULL,
    use_date    date,
    quantity    INTEGER,
    used_for    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_landproduct PRIMARY KEY (id)
);

CREATE TABLE mastitis
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diagnose_date date,
    mastitis_type VARCHAR(255),
    cmt_result    VARCHAR(255),
    ad            VARCHAR(255),
    ae            VARCHAR(255),
    pd            VARCHAR(255),
    pe            VARCHAR(255),
    animal_id     BIGINT,
    CONSTRAINT pk_mastitis PRIMARY KEY (id)
);

CREATE TABLE medication
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    application_date date,
    applied_dose     VARCHAR(255)                            NOT NULL,
    application_way  VARCHAR(255)                            NOT NULL,
    product_id       BIGINT,
    animal_id        BIGINT,
    CONSTRAINT pk_medication PRIMARY KEY (id)
);

CREATE TABLE perennial_anual_forage
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id    BIGINT                                  NOT NULL,
    type           VARCHAR(255),
    price          DOUBLE PRECISION,
    forage         VARCHAR(255),
    area           DOUBLE PRECISION,
    average_cost   DOUBLE PRECISION,
    util_life      INTEGER,
    formation_date date,
    note           VARCHAR(255),
    CONSTRAINT pk_perennialanualforage PRIMARY KEY (id)
);

CREATE TABLE permission
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_permission PRIMARY KEY (id)
);

CREATE TABLE plague
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plague_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_plague PRIMARY KEY (id)
);

CREATE TABLE pregnancy_diagnose
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diagnose_date date,
    lastia        date,
    animal_id     BIGINT,
    CONSTRAINT pk_pregnancydiagnose PRIMARY KEY (id)
);

CREATE TABLE product
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    description         VARCHAR(255)                            NOT NULL,
    application_way     VARCHAR(255)                            NOT NULL,
    active_principle_id BIGINT,
    category_id         BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE product_category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_productcategory PRIMARY KEY (id)
);

CREATE TABLE property
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    ocupation_area VARCHAR(255),
    total_area     DECIMAL,
    soil_map       BYTEA,
    latitude       DECIMAL,
    longitude      DECIMAL,
    leased         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_property PRIMARY KEY (id)
);

CREATE TABLE property_collaborator
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id       BIGINT                                  NOT NULL,
    collaborator_name VARCHAR(255)                            NOT NULL,
    work_hours        INTEGER                                 NOT NULL,
    work_days         INTEGER                                 NOT NULL,
    CONSTRAINT pk_propertycollaborator PRIMARY KEY (id)
);

CREATE TABLE property_equip_improve
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id       BIGINT                                  NOT NULL,
    type              VARCHAR(255)                            NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    quantity          INTEGER,
    unity_value       DECIMAL,
    percentage_cattle DECIMAL,
    util_life         INTEGER,
    aquisition_date   date,
    value_cattle      DECIMAL,
    CONSTRAINT pk_propertyequipimprove PRIMARY KEY (id)
);

CREATE TABLE property_technician
(
    user_id     BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    CONSTRAINT pk_propertytechnician PRIMARY KEY (user_id, property_id)
);

CREATE TABLE region
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_region PRIMARY KEY (id)
);

CREATE TABLE user_permission
(
    user_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_userpermission PRIMARY KEY (user_id, permission_id)
);

CREATE TABLE user_region
(
    user_id   BIGINT NOT NULL,
    region_id BIGINT NOT NULL,
    CONSTRAINT pk_userregion PRIMARY KEY (user_id, region_id)
);

CREATE TABLE users
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username              VARCHAR(255)                            NOT NULL,
    display_name          VARCHAR(255)                            NOT NULL,
    password              VARCHAR(255)                            NOT NULL,
    cpf                   VARCHAR(255),
    city                  VARCHAR(255),
    cep                   VARCHAR(255),
    street                VARCHAR(255),
    house_number          VARCHAR(255),
    phone                 VARCHAR(255),
    professional_register VARCHAR(255),
    graduation_year       VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_permission
(
    permission_id BIGINT NOT NULL,
    user_id       BIGINT NOT NULL,
    CONSTRAINT pk_users_permission PRIMARY KEY (permission_id, user_id)
);

CREATE TABLE vegetable_disease
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    infestation_type VARCHAR(255)                            NOT NULL,
    date             date,
    property_id      BIGINT                                  NOT NULL,
    culture_id       BIGINT                                  NOT NULL,
    disease_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_vegetabledisease PRIMARY KEY (id)
);

CREATE TABLE vegetable_plague
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    infestation_type VARCHAR(255)                            NOT NULL,
    date             date,
    property_id      BIGINT                                  NOT NULL,
    culture_id       BIGINT                                  NOT NULL,
    plague_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_vegetableplague PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_cpf UNIQUE (cpf);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE animal_diseases
    ADD CONSTRAINT FK_ANIMALDISEASES_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (id);

ALTER TABLE animal_purchases
    ADD CONSTRAINT FK_ANIMALPURCHASES_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (id);

ALTER TABLE animal_sales
    ADD CONSTRAINT FK_ANIMALSALES_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (id);

ALTER TABLE animal
    ADD CONSTRAINT FK_ANIMAL_ON_ANIMALMOTHER FOREIGN KEY (animal_mother_id) REFERENCES animal (id);

ALTER TABLE animal
    ADD CONSTRAINT FK_ANIMAL_ON_BREED FOREIGN KEY (breed_id) REFERENCES breed (id);

ALTER TABLE animal
    ADD CONSTRAINT FK_ANIMAL_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE city
    ADD CONSTRAINT FK_CITY_ON_CITYREGION FOREIGN KEY (city_region_id) REFERENCES region (id);

ALTER TABLE forage_disponibility
    ADD CONSTRAINT FK_FORAGEDISPONIBILITY_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE insemination
    ADD CONSTRAINT FK_INSEMINATION_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (id);

ALTER TABLE land_product
    ADD CONSTRAINT FK_LANDPRODUCT_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE mastitis
    ADD CONSTRAINT FK_MASTITIS_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (id);

ALTER TABLE medication
    ADD CONSTRAINT FK_MEDICATION_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (id);

ALTER TABLE medication
    ADD CONSTRAINT FK_MEDICATION_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE perennial_anual_forage
    ADD CONSTRAINT FK_PERENNIALANUALFORAGE_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE pregnancy_diagnose
    ADD CONSTRAINT FK_PREGNANCYDIAGNOSE_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_ACTIVEPRINCIPLE FOREIGN KEY (active_principle_id) REFERENCES active_principle (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES product_category (id);

ALTER TABLE property_collaborator
    ADD CONSTRAINT FK_PROPERTYCOLLABORATOR_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE property_equip_improve
    ADD CONSTRAINT FK_PROPERTYEQUIPIMPROVE_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE property_technician
    ADD CONSTRAINT FK_PROPERTYTECHNICIAN_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE property_technician
    ADD CONSTRAINT FK_PROPERTYTECHNICIAN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE property
    ADD CONSTRAINT FK_PROPERTY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_permission
    ADD CONSTRAINT FK_USERPERMISSION_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES permission (id);

ALTER TABLE user_permission
    ADD CONSTRAINT FK_USERPERMISSION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_region
    ADD CONSTRAINT FK_USERREGION_ON_REGION FOREIGN KEY (region_id) REFERENCES region (id);

ALTER TABLE user_region
    ADD CONSTRAINT FK_USERREGION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE vegetable_disease
    ADD CONSTRAINT FK_VEGETABLEDISEASE_ON_CULTURE FOREIGN KEY (culture_id) REFERENCES culture (id);

ALTER TABLE vegetable_disease
    ADD CONSTRAINT FK_VEGETABLEDISEASE_ON_DISEASE FOREIGN KEY (disease_id) REFERENCES disease (id);

ALTER TABLE vegetable_disease
    ADD CONSTRAINT FK_VEGETABLEDISEASE_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE vegetable_plague
    ADD CONSTRAINT FK_VEGETABLEPLAGUE_ON_CULTURE FOREIGN KEY (culture_id) REFERENCES culture (id);

ALTER TABLE vegetable_plague
    ADD CONSTRAINT FK_VEGETABLEPLAGUE_ON_PLAGUE FOREIGN KEY (plague_id) REFERENCES plague (id);

ALTER TABLE vegetable_plague
    ADD CONSTRAINT FK_VEGETABLEPLAGUE_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (id);

ALTER TABLE users_permission
    ADD CONSTRAINT fk_useper_on_permission FOREIGN KEY (permission_id) REFERENCES permission (id);

ALTER TABLE users_permission
    ADD CONSTRAINT fk_useper_on_user FOREIGN KEY (user_id) REFERENCES users (id);