CREATE TABLE active_principle
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT active_principle_pkey PRIMARY KEY (id)
);

CREATE TABLE animal
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id      BIGINT                                  NOT NULL,
    animal_mother_id BIGINT                                  NOT NULL,
    breed_id         BIGINT                                  NOT NULL,
    type             VARCHAR(255),
    identifier       VARCHAR(255),
    gender           VARCHAR(255),
    born_condition   VARCHAR(255),
    born_date        date,
    born_weight      FLOAT,
    previous_weight  FLOAT,
    current_weight   FLOAT,
    ecc              FLOAT,
    CONSTRAINT animal_pkey PRIMARY KEY (id)
);

CREATE TABLE animal_diseases
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diagnosis      VARCHAR(255),
    diagnosis_date date,
    animal_id      BIGINT,
    CONSTRAINT animal_diseases_pkey PRIMARY KEY (id)
);

CREATE TABLE animal_purchases
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_purchase date,
    birth_date    date,
    value         DECIMAL,
    animal_id     BIGINT,
    CONSTRAINT animal_purchases_pkey PRIMARY KEY (id)
);

CREATE TABLE animal_sales
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_sale   date,
    reason      SMALLINT,
    value       DECIMAL,
    destination SMALLINT,
    animal_id   BIGINT,
    CONSTRAINT animal_sales_pkey PRIMARY KEY (id)
);

CREATE TABLE breed
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    breed_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT breed_pkey PRIMARY KEY (id)
);

CREATE TABLE change_password
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recuperation_code    VARCHAR(255),
    code_submission_date TIMESTAMP WITHOUT TIME ZONE,
    recuperation_email   VARCHAR(255),
    user_display_name    VARCHAR(255),
    new_password         VARCHAR(255),
    CONSTRAINT change_password_pkey PRIMARY KEY (id)
);

CREATE TABLE city
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    city_region_id BIGINT                                  NOT NULL,
    CONSTRAINT city_pkey PRIMARY KEY (id)
);

CREATE TABLE culture
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    culture_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT culture_pkey PRIMARY KEY (id)
);

CREATE TABLE disease
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    disease_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT disease_pkey PRIMARY KEY (id)
);

CREATE TABLE email
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_ref       VARCHAR(255),
    email_from      VARCHAR(255),
    email_to        VARCHAR(255),
    subject         VARCHAR(255),
    text            TEXT,
    send_date_email TIMESTAMP WITHOUT TIME ZONE,
    status_email    VARCHAR(255),
    CONSTRAINT email_pkey PRIMARY KEY (id)
);

CREATE TABLE forage_disponibility
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        date,
    forage      VARCHAR(255),
    entry       FLOAT,
    residue     FLOAT,
    kg          FLOAT,
    picket_area FLOAT,
    efficiency  FLOAT,
    num_cows    DECIMAL,
    kg_cows     FLOAT,
    property_id BIGINT                                  NOT NULL,
    CONSTRAINT forage_disponibility_pkey PRIMARY KEY (id)
);

CREATE TABLE insemination
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ia_date   date,
    bull      VARCHAR(255),
    animal_id BIGINT,
    CONSTRAINT insemination_pkey PRIMARY KEY (id)
);

CREATE TABLE land_product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id BIGINT                                  NOT NULL,
    use_date    date,
    quantity    INTEGER,
    used_for    VARCHAR(255)                            NOT NULL,
    CONSTRAINT land_product_pkey PRIMARY KEY (id)
);

CREATE TABLE mastitis
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diagnose_date date,
    mastitis_type VARCHAR(255),
    cmt_result    VARCHAR(255),
    ad            VARCHAR(255),
    ae            VARCHAR(255),
    pd            VARCHAR(255),
    pe            VARCHAR(255),
    animal_id     BIGINT,
    CONSTRAINT mastitis_pkey PRIMARY KEY (id)
);

CREATE TABLE medication
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    application_date date,
    applied_dose     VARCHAR(255)                            NOT NULL,
    application_way  VARCHAR(255)                            NOT NULL,
    product_id       BIGINT,
    animal_id        BIGINT,
    CONSTRAINT medication_pkey PRIMARY KEY (id)
);

CREATE TABLE perennial_anual_forage
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id    BIGINT                                  NOT NULL,
    type           VARCHAR(255),
    price          DOUBLE PRECISION,
    forage         VARCHAR(255),
    area           DOUBLE PRECISION,
    average_cost   DOUBLE PRECISION,
    util_life      INTEGER,
    formation_date date,
    note           VARCHAR(255),
    CONSTRAINT perennial_anual_forage_pkey PRIMARY KEY (id)
);

CREATE TABLE permission
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT permission_pkey PRIMARY KEY (id)
);

CREATE TABLE plague
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plague_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT plague_pkey PRIMARY KEY (id)
);

CREATE TABLE pregnancy_diagnose
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diagnose_date date,
    lastia        date,
    animal_id     BIGINT,
    CONSTRAINT pregnancy_diagnose_pkey PRIMARY KEY (id)
);

CREATE TABLE product
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    description         VARCHAR(255)                            NOT NULL,
    application_way     VARCHAR(255)                            NOT NULL,
    active_principle_id BIGINT,
    category_id         BIGINT,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE product_category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    CONSTRAINT product_category_pkey PRIMARY KEY (id)
);

CREATE TABLE property
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    ocupation_area VARCHAR(255),
    total_area     DECIMAL,
    soil_map       BYTEA,
    latitude       DECIMAL,
    longitude      DECIMAL,
    leased         BOOLEAN                                 NOT NULL,
    CONSTRAINT property_pkey PRIMARY KEY (id)
);

CREATE TABLE property_collaborator
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id       BIGINT                                  NOT NULL,
    collaborator_name VARCHAR(255)                            NOT NULL,
    work_hours        INTEGER                                 NOT NULL,
    work_days         INTEGER                                 NOT NULL,
    CONSTRAINT property_collaborator_pkey PRIMARY KEY (id)
);

CREATE TABLE property_equip_improve
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id       BIGINT                                  NOT NULL,
    type              VARCHAR(255)                            NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    quantity          INTEGER,
    unity_value       DECIMAL,
    percentage_cattle DECIMAL,
    util_life         INTEGER,
    aquisition_date   date,
    value_cattle      DECIMAL,
    CONSTRAINT property_equip_improve_pkey PRIMARY KEY (id)
);

CREATE TABLE property_technician
(
    user_id     BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    CONSTRAINT property_technician_pkey PRIMARY KEY (user_id, property_id)
);

CREATE TABLE region
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT region_pkey PRIMARY KEY (id)
);

CREATE TABLE user_permission
(
    user_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT user_permission_pkey PRIMARY KEY (user_id, permission_id)
);

CREATE TABLE user_region
(
    user_id   BIGINT NOT NULL,
    region_id BIGINT NOT NULL,
    CONSTRAINT user_region_pkey PRIMARY KEY (user_id, region_id)
);

CREATE TABLE users
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username              VARCHAR(255)                            NOT NULL,
    display_name          VARCHAR(255)                            NOT NULL,
    password              VARCHAR(255)                            NOT NULL,
    cpf                   VARCHAR(255),
    city                  VARCHAR(255),
    cep                   VARCHAR(255),
    street                VARCHAR(255),
    house_number          VARCHAR(255),
    phone                 VARCHAR(255),
    professional_register VARCHAR(255),
    graduation_year       VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE users_permission
(
    permission_id BIGINT NOT NULL,
    user_id       BIGINT NOT NULL,
    CONSTRAINT users_permission_pkey PRIMARY KEY (permission_id, user_id)
);

CREATE TABLE vegetable_disease
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    infestation_type VARCHAR(255)                            NOT NULL,
    date             date,
    property_id      BIGINT                                  NOT NULL,
    culture_id       BIGINT                                  NOT NULL,
    disease_id       BIGINT                                  NOT NULL,
    CONSTRAINT vegetable_disease_pkey PRIMARY KEY (id)
);

CREATE TABLE vegetable_plague
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    infestation_type VARCHAR(255)                            NOT NULL,
    date             date,
    property_id      BIGINT                                  NOT NULL,
    culture_id       BIGINT                                  NOT NULL,
    plague_id        BIGINT                                  NOT NULL,
    CONSTRAINT vegetable_plague_pkey PRIMARY KEY (id)
);